### ISSUE TITLE
插件命令运行失败

### ISSUE THREAD

**Issue by Jim-CN** [WadeChenn/Plex-Tools#14]
环境描述：Unraid6.11.3，Plex和MR都是docker部署，custom br0网络方式，MR1.9.37，Plex工具箱1.0。
问题描述：手工启动插件选择电影媒体库运行整理全库，运行3-5分钟后终止，报连接plex超时，多次尝试都是如此，报错时整理的影片不是同一部，已整理的电影显示正常。
日志：
 2023/02/15 11:22:49 - MBotExecutor_0 - INFO: 首字母排序完成 BHLT
 2023/02/15 11:22:49 - MBotExecutor_0 - INFO: 辩护人
 2023/02/15 11:22:50 - MBotExecutor_0 - INFO: 辩护人
 2023/02/15 11:22:50 - MBotExecutor_0 - INFO: Fanart筛选完成
 2023/02/15 11:22:52 - MBotExecutor_0 - INFO: 标签翻译整理完成
 [<Genre:923:历史>, <Genre:61:剧情>, <Genre:127317:豆瓣TOP-250>, <Genre:108303:DouBanTop250>]
 2023/02/15 11:22:52 - MBotExecutor_0 - INFO: 首字母排序完成 BHR
 2023/02/15 11:22:52 - MBotExecutor_0 - INFO: 冰海陷落
 2023/02/15 11:22:54 - MBotExecutor_0 - INFO: 冰海陷落
 2023/02/15 11:22:54 - MBotExecutor_0 - INFO: Fanart筛选完成
 2023/02/15 11:22:59 - MBotExecutor_0 - INFO: 标签翻译整理完成
 [<Genre:156:惊悚>, <Genre:69404:动作>]
 2023/02/15 11:22:59 - MBotExecutor_0 - INFO: 首字母排序完成 BHXL
 2023/02/15 11:22:59 - MBotExecutor_0 - INFO: 被解救的姜戈
 2023/02/15 11:23:01 - MBotExecutor_0 - INFO: 被解救的姜戈
 2023/02/15 11:23:01 - MBotExecutor_0 - INFO: Fanart筛选完成
 2023/02/15 11:23:03 - ThreadPoolExecutor-4_0 - INFO: 开始同步站点资源信息...
2023/02/15 11:23:09 - MBotExecutor_0 - INFO: 标签翻译整理完成
 [<Genre:61:剧情>, <Genre:435:西部>, <Genre:127317:豆瓣TOP-250>, <Genre:127316:IMDB-TOP-250>, <Genre:108303:DouBanTop250>, <Genre:108302:IMDBtop250>]
 2023/02/15 11:23:09 - MBotExecutor_0 - INFO: 首字母排序完成 BJJDJG
 2023/02/15 11:23:09 - MBotExecutor_0 - INFO: 搏击俱乐部
 2023/02/15 11:23:41 - MBotExecutor_0 - ERROR: 插件命令运行失败
Traceback (most recent call last):
  File "/dependencies/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/dependencies/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/dependencies/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/dependencies/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/dependencies/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/dependencies/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/dependencies/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/dependencies/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.124.207', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/core/plugins/__init__.py", line 144, in mbot.core.plugins.__init__.PluginCommand.__call__
  File "/data/plugins/plexsortout/command.py", line 26, in select_data
    plexst.process_all(library)
  File "/data/plugins/plexsortout/plexsortout.py", line 358, in process_all
    self.process_fanart(video)
  File "/data/plugins/plexsortout/plexsortout.py", line 205, in process_fanart
    video.setPoster(poster)
  File "/dependencies/plexapi/mixins.py", line 468, in setPoster
    poster.select()
  File "/dependencies/plexapi/media.py", line 972, in select
    self._server.query(data, method=self._server._session.put)
  File "/dependencies/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/dependencies/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/dependencies/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/dependencies/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/dependencies/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.124.207', port=32400): Read timed out. (read timeout=30)

**Comment by Zeta-ZhaoLi** [comment]
一样的问题，整理电影库就报错超时，电视库就正常

**Comment by Jim-CN** [comment]
我整理电视库也是一样的报错

**Comment by Zeta-ZhaoLi** [comment]
> 我整理电视库也是一样的报错

我发现是不能整理标签，勾选掉标签翻译和TOP250就可以工作了

**Comment by Jim-CN** [comment]
> > 我整理电视库也是一样的报错
> 
> 我发现是不能整理标签，勾选掉标签翻译和TOP250就可以工作了

我取消勾选标签翻译和top也是一样报错，只是坚持的时间长了点而已

**Comment by WadeChenn** [comment]
> 
超时的问题把mr的docker模式切换为host试试

**Comment by Zeta-ZhaoLi** [comment]
> > 
> 
> 超时的问题把mr的docker模式切换为host试试

我的情况是电视剧类的可以完全正常运行，电影类的第一个开始就卡在整理标签，不像楼主还能整理几个。

我把mr的docker切换到host模式反而连不到plex了......
但是不整理标签就能全部运行成功，这应该是已经连接到了plex吧。
我之前用单独功能的插件也会偶尔失败，一般是plex自己在整理资料库，那时候重启一下plex再运行插件就能成功。但是现在这个方法就不行了

2023/02/17 11:10:19 - Thread-150 - INFO: 开始获取媒体库
2023/02/17 11:10:19 - Thread-150 - INFO: 其他电影
2023/02/17 11:10:19 - Thread-150 - INFO: 动画电影
2023/02/17 11:10:19 - Thread-150 - INFO: 电影
2023/02/17 11:10:19 - Thread-150 - INFO: 电视动画
2023/02/17 11:10:19 - Thread-150 - INFO: 电视节目
2023/02/17 11:10:19 - Thread-150 - INFO: 音乐
2023/02/17 11:10:19 - Thread-150 - INFO: 其他影片
2023/02/17 11:10:19 - MBotExecutor_0 - INFO: 电影
2023/02/17 11:10:25 - MBotExecutor_0 - INFO: 007：大战皇家赌场
2023/02/17 11:10:25 - MBotExecutor_0 - INFO: 007：大战皇家赌场
2023/02/17 11:10:25 - MBotExecutor_0 - INFO: Fanart筛选完成
2023/02/17 11:10:55 - MBotExecutor_0 - ERROR: 插件命令运行失败
Traceback (most recent call last):
  File "/dependencies/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/dependencies/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/dependencies/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/dependencies/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/dependencies/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/dependencies/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/dependencies/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/dependencies/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.1.202', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/core/plugins/__init__.py", line 144, in mbot.core.plugins.__init__.PluginCommand.__call__
  File "/data/plugins/plexsortout/command.py", line 26, in select_data
    plexst.process_all(library)
  File "/data/plugins/plexsortout/plexsortout.py", line 362, in process_all
    self.process_tag(video)
  File "/data/plugins/plexsortout/plexsortout.py", line 261, in process_tag
    video.reload()
  File "/dependencies/plexapi/base.py", line 368, in reload
    return self._reload(key=key, **kwargs)
  File "/dependencies/plexapi/base.py", line 377, in _reload
    data = self._server.query(key)
  File "/dependencies/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/dependencies/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/dependencies/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/dependencies/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/dependencies/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.202', port=32400): Read timed out. (read timeout=30)

**Comment by yangc-vip** [comment]
所有错误 都是在 “Fanart 精美封面筛选完成”日志之前

错误触发时间不确定。有时候一分钟。有时候几分钟。反正500部电影试了十多次没有处理完。



2023/03/18 20:22:35 - MBotExecutor_0 - INFO: 「PLEX 工具箱」开始处理「占有者」
2023/03/18 20:23:06 - MBotExecutor_0 - ERROR: 插件命令运行失败
Traceback (most recent call last):
  File "/dependencies/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/dependencies/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dependencies/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/dependencies/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/dependencies/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/dependencies/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/dependencies/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/dependencies/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/dependencies/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.10.10.56', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbot/core/plugins/__init__.py", line 144, in mbot.core.plugins.__init__.PluginCommand.__call__
  File "/data/plugins/plexsortout/command.py", line 28, in select_data
    plexst.process_all(library,sortoutNum)
  File "/data/plugins/plexsortout/plexsortout.py", line 384, in process_all
    self.process_fanart(video)
  File "/data/plugins/plexsortout/plexsortout.py", line 212, in process_fanart
    video.setPoster(poster)
  File "/dependencies/plexapi/mixins.py", line 468, in setPoster
    poster.select()
  File "/dependencies/plexapi/media.py", line 980, in select
    self._server.query(data, method=self._server._session.put)
  File "/dependencies/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/dependencies/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/dependencies/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/dependencies/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/dependencies/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.10.10.56', port=32400): Read timed out. (read timeout=30)

**Comment by 522654518** [comment]
> 所有错误 都是在 “Fanart 精美封面筛选完成”日志之前
> 
> 错误触发时间不确定。有时候一分钟。有时候几分钟。反正500部电影试了十多次没有处理完。
> 
> 2023/03/18 20:22:35 - MBotExecutor_0 - INFO: 「PLEX 工具箱」开始处理「占有者」 2023/03/18 20:23:06 - MBotExecutor_0 - ERROR: 插件命令运行失败 Traceback (most recent call last): File "/dependencies/urllib3/connectionpool.py", line 449, in _make_request six.raise_from(e, None) File "", line 3, in raise_from File "/dependencies/urllib3/connectionpool.py", line 444, in _make_request httplib_response = conn.getresponse() File "/usr/local/lib/python3.9/http/client.py", line 1347, in getresponse response.begin() File "/usr/local/lib/python3.9/http/client.py", line 307, in begin version, status, reason = self._read_status() File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/usr/local/lib/python3.9/socket.py", line 704, in readinto return self._sock.recv_into(b) socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/dependencies/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/dependencies/urllib3/connectionpool.py", line 787, in urlopen retries = retries.increment( File "/dependencies/urllib3/util/retry.py", line 550, in increment raise six.reraise(type(error), error, _stacktrace) File "/dependencies/urllib3/packages/six.py", line 770, in reraise raise value File "/dependencies/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/dependencies/urllib3/connectionpool.py", line 451, in _make_request self._raise_timeout(err=e, url=url, timeout_value=read_timeout) File "/dependencies/urllib3/connectionpool.py", line 340, in _raise_timeout raise ReadTimeoutError( urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.10.10.56', port=32400): Read timed out. (read timeout=30)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "mbot/core/plugins/**init**.py", line 144, in mbot.core.plugins.**init**.PluginCommand.**call** File "/data/plugins/plexsortout/command.py", line 28, in select_data plexst.process_all(library,sortoutNum) File "/data/plugins/plexsortout/plexsortout.py", line 384, in process_all self.process_fanart(video) File "/data/plugins/plexsortout/plexsortout.py", line 212, in process_fanart video.setPoster(poster) File "/dependencies/plexapi/mixins.py", line 468, in setPoster poster.select() File "/dependencies/plexapi/media.py", line 980, in select self._server.query(data, method=self._server._session.put) File "/dependencies/plexapi/server.py", line 745, in query response = method(url, headers=headers, timeout=timeout, **kwargs) File "/dependencies/requests/sessions.py", line 647, in put return self.request("PUT", url, data=data, **kwargs) File "/dependencies/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/dependencies/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/dependencies/requests/adapters.py", line 578, in send raise ReadTimeout(e, request=request) requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.10.10.56', port=32400): Read timed out. (read timeout=30)

把精选封面功能取消 就不会超时了  是精选封面的锅

**Comment by Zeta-ZhaoLi** [comment]
最近我发现是什么原因了，官方docker版的plex的数据库性能太差，操作多了就容易繁忙无响应，然后插件就显示超时错误。
我用官方的windows版，或者linuxserver的docker就正常了。

**Comment by 522654518** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
